apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: release-readiness
  labels:
    app: release-readiness
spec:
  to:
    kind: Service
    name: release-readiness
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
