apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: build-dashboard
  labels:
    app: build-dashboard
spec:
  to:
    kind: Service
    name: build-dashboard
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
